# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlfmt < Formula
  desc "Formats yaml files."
  homepage "https://devopy.io/"
  url "https://github.com/devopyio/yamlfmt/releases/download/v1.0.1/yamlfmt_1.0.1_darwin_amd64.tar.gz"
  version "1.0.1"
  sha256 "12d848da847c934183b326ed437efad336d9d7398a12fd11d94767b97213672b"

  def install
    bin.install "yamlfmt"
  end

  def caveats; <<~EOS
    cat example.yaml | yamlfmt or yamlfmt -filename example.yaml
  EOS
  end
end
